// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";
import tinycolor from "tinycolor2";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} hexValue - e.g. #FF0000
 * @param {Big} darkenPercentage
 * @returns {Promise.<string>}
 */
export async function JS_Color_Darken(hexValue, darkenPercentage) {
	// BEGIN USER CODE
	const color = tinycolor(hexValue);
	return color.darken(darkenPercentage).toHexString(); // "#ff00ff"
	// END USER CODE
}
